name: flutter_test_webspark_shortest_way_app_02_24
description: "Test project"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  http: ^1.2.1
  hexcolor: ^3.0.1
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5 
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
